### ISSUE TITLE
Green Lighting Bug?

### ISSUE THREAD

**Issue by lenship2** [Trico-Everfire/VTF_Edit_Revitalized#22]
Exporting a basetexture .vtf through this app, compared to VTFEdit Reloaded, seems to have a weird affect of adding a green tint to the lighting of a map with the texture in it. 

I haven't thoroughly tested every factor that might've caused it, but for reference, the textures I was creating had the following custom parameters:

- 2048x2048 dimensions
- RGBA8888 colors
- Quadratic mipmaps
- VTF version 7.6, with a compression level of 9 (although 7.5 also resulted in the same issue in Portal 2)

This seems to be completely unrelated to the VTFEdit DXT bug that adds a green tint to the basetexture itself, and seems to only affect the VRAD compiler (I could be wrong though, this is just what I've observed). It also so far seems to be independent of the Source engine branch as well, as both the Strata branch and a 7.5 version of the texture in Portal 2 resulted in the same green lighting.

**Comment by Trico-Everfire** [comment]
Hello! You seem to not compute reflectivity. In the Advanced tab, there's a checkbox for computing reflectivity. It's sole purpose is for VRAD to know how to compile the reflectivity of the texture. Without this checked, it'll use the reflectivity values set in the General tab. It's placement is a bit wonky and will be fixed in v1.0. If this does fix your issue then I'll close it as resolved. If not, wait for v1.0, as it's a complete overhaul of all major systems regarding VTF creation.
